import express from 'express';
import cors from 'cors';
import { config } from './env.js';
import { healthCheck } from './db/index.js';
import { notFound, errorHandler } from './lib/errors.js';
import authRoutes from './routes/auth.js';
import farmRoutes from './routes/farms.js';
import cowRoutes from './routes/cows.js';
import milkRoutes from './routes/milk.js';
import dashboardRoutes from './routes/dashboard.js';
import predictionRoutes from './routes/predictions.js';
import analyticsRoutes from './routes/analytics.js';
import financeRoutes from './routes/finance.js';
import weatherRoutes from './routes/weather.js';
import notificationRoutes from './routes/notifications.js';
import sustainabilityRoutes from './routes/sustainability.js';
import aiRoutes from './routes/ai.js';
import galleryRoutes from './routes/gallery.js';
import customerRoutes from './routes/customers.js';
import employeeRoutes from './routes/employees.js';
import feedConsumptionRoutes from './routes/feed-consumption.js';
import treatmentRoutes from './routes/treatments.js';
import taskRoutes from './routes/tasks.js';
import dailyActivityRoutes from './routes/daily-activities.js';
import mapRoutes from './routes/map.js';
import heatDetectionRoutes from './routes/heat-detection.js';
import breedingRoutes from './routes/breeding.js';
import semenRoutes from './routes/semen.js';
import calvingRoutes from './routes/calving.js';
import twinBirthRoutes from './routes/twin-births.js';
import fertilityRoutes from './routes/fertility.js';
import geneticsRoutes from './routes/genetics.js';
import breedingRecommendationRoutes from './routes/breeding-recommendations.js';
import shiftRoutes from './routes/shifts.js';
import trainingRoutes from './routes/training.js';
import performanceRoutes from './routes/performance.js';
import leaveRoutes from './routes/leave.js';
import messageRoutes from './routes/messages.js';
import faceRoutes from './routes/face.js';
import gpsRoutes from './routes/gps.js';
import attendanceRoutes from './routes/attendance.js';
import payrollRoutes from './routes/payroll.js';


const app = express();
app.use(cors());
app.use(express.json({ limit: '1mb' }));

app.get('/health', async (_req, res) => {
  res.json({ status: 'ok', db: await healthCheck(), time: new Date().toISOString() });
});

const api = express.Router();
api.get('/', (_req, res) => res.json({ name: 'Smart Dairy API', version: '0.1.0' }));
api.use('/auth', authRoutes);
api.use('/farms', farmRoutes);
api.use('/cows', cowRoutes);
api.use('/milk-records', milkRoutes);
api.use('/dashboard', dashboardRoutes);
api.use('/predictions', predictionRoutes);
api.use('/analytics', analyticsRoutes);
api.use('/finance', financeRoutes);
api.use('/weather', weatherRoutes);
api.use('/notifications', notificationRoutes);
api.use('/sustainability', sustainabilityRoutes);
api.use('/ai', aiRoutes);
api.use('/gallery', galleryRoutes);
api.use('/customers', customerRoutes);
api.use('/employees', employeeRoutes);
api.use('/feed-records', feedConsumptionRoutes);
api.use('/treatments', treatmentRoutes);
api.use('/tasks', taskRoutes);
api.use('/daily-activities', dailyActivityRoutes);
api.use('/map', mapRoutes);
api.use('/heat-detection', heatDetectionRoutes);
api.use('/breeding', breedingRoutes);
api.use('/semen', semenRoutes);
api.use('/calving', calvingRoutes);
api.use('/twin-births', twinBirthRoutes);
api.use('/fertility', fertilityRoutes);
api.use('/genetics', geneticsRoutes);
api.use('/breeding-recommendations', breedingRecommendationRoutes);
api.use('/shifts', shiftRoutes);
api.use('/training', trainingRoutes);
api.use('/performance', performanceRoutes);
api.use('/leave', leaveRoutes);
api.use('/messages', messageRoutes);
api.use('/face', faceRoutes);
api.use('/gps', gpsRoutes);
api.use('/attendance', attendanceRoutes);
api.use('/payroll', payrollRoutes);

app.use('/api/v1', api);
app.use(notFound);
app.use(errorHandler);

app.listen(config.port, () => {
  console.log(`🐄 Dairy API listening on http://localhost:${config.port} (env=${config.env})`);
});
